CREATE TABLE MOVIE (
	ID VARCHAR(40) PRIMARY KEY,
	NAME VARCHAR(255),
	GENRE VARCHAR(255),
	UNIQUE (NAME)
);

CREATE INDEX MOVIE_ID_IDX ON MOVIE(ID);

CREATE TABLE USER (
	ID VARCHAR(40) PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	DOB DATE NOT NULL,
	UNIQUE (NAME)
);

CREATE INDEX USER_ID_IDX ON USER(ID);

CREATE TABLE MOVIE_REVIEW (
	MOVIE_ID VARCHAR(40),
	USER_ID VARCHAR(40),
	RATING INT NOT NULL,
	TIME_WATCHED TIMESTAMP NOT NULL,
	FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (MOVIE_ID, USER_ID)
);

CREATE INDEX REVIEW_MOVIE_ID_IDX ON MOVIE_REVIEW(MOVIE_ID,USER_ID);

